'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class all
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Roleta.all", GetType(all).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Friend Shared ReadOnly Property but_login() As String
            Get
                Return ResourceManager.GetString("but_login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign Up.
        '''</summary>
        Friend Shared ReadOnly Property but_SignUp() As String
            Get
                Return ResourceManager.GetString("but_SignUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add user.
        '''</summary>
        Friend Shared ReadOnly Property but_signup_add() As String
            Get
                Return ResourceManager.GetString("but_signup_add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information.
        '''</summary>
        Friend Shared ReadOnly Property Informacao() As String
            Get
                Return ResourceManager.GetString("Informacao", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password is wrong.
        '''</summary>
        Friend Shared ReadOnly Property lbl_error_login() As String
            Get
                Return ResourceManager.GetString("lbl_error_login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password:.
        '''</summary>
        Friend Shared ReadOnly Property lbl_pass() As String
            Get
                Return ResourceManager.GetString("lbl_pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign Up.
        '''</summary>
        Friend Shared ReadOnly Property lbl_signup() As String
            Get
                Return ResourceManager.GetString("lbl_signup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Name.
        '''</summary>
        Friend Shared ReadOnly Property lbl_signup_Fname() As String
            Get
                Return ResourceManager.GetString("lbl_signup_Fname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Name.
        '''</summary>
        Friend Shared ReadOnly Property lbl_signup_Lname() As String
            Get
                Return ResourceManager.GetString("lbl_signup_Lname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property lbl_signup_pass() As String
            Get
                Return ResourceManager.GetString("lbl_signup_pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retype password.
        '''</summary>
        Friend Shared ReadOnly Property lbl_signup_pass2() As String
            Get
                Return ResourceManager.GetString("lbl_signup_pass2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username.
        '''</summary>
        Friend Shared ReadOnly Property lbl_signup_user() As String
            Get
                Return ResourceManager.GetString("lbl_signup_user", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User:.
        '''</summary>
        Friend Shared ReadOnly Property lbl_user() As String
            Get
                Return ResourceManager.GetString("lbl_user", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Friend Shared ReadOnly Property me_title() As String
            Get
                Return ResourceManager.GetString("me_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The database was corrupted..
        '''</summary>
        Friend Shared ReadOnly Property msg1_line1() As String
            Get
                Return ResourceManager.GetString("msg1_line1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It has been reset.
        '''</summary>
        Friend Shared ReadOnly Property msg1_line2() As String
            Get
                Return ResourceManager.GetString("msg1_line2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Important.
        '''</summary>
        Friend Shared ReadOnly Property msg1_title1() As String
            Get
                Return ResourceManager.GetString("msg1_title1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User doesn&apos;t exist.
        '''</summary>
        Friend Shared ReadOnly Property msg2_linha1() As String
            Get
                Return ResourceManager.GetString("msg2_linha1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Want to add new user?.
        '''</summary>
        Friend Shared ReadOnly Property msg2_linha2() As String
            Get
                Return ResourceManager.GetString("msg2_linha2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add new user.
        '''</summary>
        Friend Shared ReadOnly Property msg2_title1() As String
            Get
                Return ResourceManager.GetString("msg2_title1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Min of 3 carateres.
        '''</summary>
        Friend Shared ReadOnly Property msg3_linha1() As String
            Get
                Return ResourceManager.GetString("msg3_linha1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign up.
        '''</summary>
        Friend Shared ReadOnly Property msg3_title1() As String
            Get
                Return ResourceManager.GetString("msg3_title1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fill in the field..
        '''</summary>
        Friend Shared ReadOnly Property msg4_linha1() As String
            Get
                Return ResourceManager.GetString("msg4_linha1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing fields.
        '''</summary>
        Friend Shared ReadOnly Property msg4_title1() As String
            Get
                Return ResourceManager.GetString("msg4_title1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passwords don&apos;t match.
        '''</summary>
        Friend Shared ReadOnly Property msg5_linha1() As String
            Get
                Return ResourceManager.GetString("msg5_linha1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User already exists.
        '''</summary>
        Friend Shared ReadOnly Property msg6_linha1() As String
            Get
                Return ResourceManager.GetString("msg6_linha1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Names can&apos;t include spaces..
        '''</summary>
        Friend Shared ReadOnly Property msg7() As String
            Get
                Return ResourceManager.GetString("msg7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User added..
        '''</summary>
        Friend Shared ReadOnly Property msg8() As String
            Get
                Return ResourceManager.GetString("msg8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Success.
        '''</summary>
        Friend Shared ReadOnly Property Sucesso() As String
            Get
                Return ResourceManager.GetString("Sucesso", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
